quarkus:
  application:
    name: relay

  http:
    port: 8080

  log:
    console:
      format: "%d{HH:mm:ss} %-5p [%c{2.}] %s%e%n"
    category:
      "com.lbg.markets.surveillance.relay":
        level: INFO



